# Watching the division by zero error that raises an exception.
print(5/0)